# Generated by Django 3.0.3 on 2020-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('crm', models.IntegerField(verbose_name='CRM')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e tempo de Criação')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Data e tempo de alteração')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
